# Internal
# ========

metaDataForamt: yaml

languageCode: ja
defaultLanguageCode: ja
hasCJKLanguage: true
defaultContentLanguage: ja

layoutDir: templates
assetDir: assets
publishDir: dist
contentDir: src/content

# URL
# ===

disablePathToLower: true
permalinks:
  posts: /posts/:year/:month/:day/:slug/
  echos: /echos/:year/:month/:day/:slug/
  notes: /notes/:slug/
  pages: /:filename/
taxonomies:
  tag: "tags"

paginate: 15
paginatePath: "pages"

disableKinds:
  - taxonomyTerm

# Content
# =======

pygmentsUseClasses: true

enableInlineShortcodes: true
enableRobotsTXT: true

summaryLength: 140

markup:
  highlight:
    codeFence: true
    guessSyntax: false
    tabWidth: 2
  goldmark:
    extensions:
      definitionList: false
      footnote: false
      linkify: false
      strikethrough: true
      table: true
      taskList: false
      typographer: false
    parser:
      attribute: false
      audoHeadingID: true
    renderer:
      unsafe: true

related:
  threashold: 80
  includeNewer: true
  indices:
    - name: tags
      weight: 100
    - name: date
      weight: 10

# Output
# ======

mediaTypes:
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  JSONFeed:
    mediaType: application/json
    baseName: jsonfeed
    isPlainText: true
  Atom:
    mediaType: application/atom+xml
    baseName: atom
    isPainText: false

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
  section:
    - HTML
    - Atom
    - RSS
    - JSONFeed
  page:
    - HTML

# Varialbes
# =========

title: カラクリスタ

params:
  profile: |-
    2004年から2020年に掛けて、もうずっと病気療養中（家事手伝い）

    ちなみに2006年ぐらいからこの名前で活動をしていますが、
    気が付けば[自分以外に著名な『にゃるら』さんが爆誕していました](/notes/nyarla-is-not-nyalra)。
  text:
    fallback:
      title: カラクリスタ
      message: なお[クレイジーな方の<br>『にゃるら』さんとは別の個体](https://the.kalaclista.com/notes/nyarla-is-not-nyalra/)です。
    home:
      label: ホーム
      title: カラクリスタ
      description: 『輝かしい青春』なんて失かった方の<br>『にゃるら』の Web サイトです。
    posts:
      label: ブログ
      title: カラクリスタ・ブログ
      name: ブログ
      description: 『輝かしい青春』なんて失かった方の<br>『にゃるら』の個人ブログです。
    echos:
      label: 雑記
      title: カラクリスタ・エコーズ
      name: エコーズ
      description: 『輝かしい青春』なんて失かった方の<br>『にゃるら』のチラシの裏っぽいモノ。
    notes:
      label: ノート
      title: カラクリスタ・ノート
      name: ノート
      description: 『輝かしい青春』なんて失かった方の<br>『にゃるら』のまとめ記事的なノートです。
    search:
      label: 検索
      title: カラクリスタ・サーチ
      name: サーチ
      description: この  Web サイトの中身を検索します。<br>なお Google Custom Search Engine 製。
      message: とは言え、検索だけですべての記事が見付かるかどうは微妙なところが……。
    archives:
      label: 過去ログ
      title: カラクリスタ・アーカイブ
      name: アーカイブ
      description: 『輝かしい青春』なんて失かった方の<br>『にゃるら』の Webサイトの過去ログです。
    notfound:
      title: カラクリスタ？
      name: ？
      description: "いわゆる 404 Page not Found。<br>ページが見付かりません。"
      message: 記事などが行方不明です。<br>もしかすると検索すると見付かるかもしれません。
    twitter:
      label: 小鳥
    note:
      label: 別所
    github:
      label: 開発
